#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAB4655A126D292E4 (coreteam@netfilter.org)
#
Name     : libnetfilter_queue
Version  : 1.0.3
Release  : 9
URL      : http://www.netfilter.org/projects/libnetfilter_queue/files/libnetfilter_queue-1.0.3.tar.bz2
Source0  : http://www.netfilter.org/projects/libnetfilter_queue/files/libnetfilter_queue-1.0.3.tar.bz2
Source99 : http://www.netfilter.org/projects/libnetfilter_queue/files/libnetfilter_queue-1.0.3.tar.bz2.sig
Summary  : netfilter userspace packet queueing library
Group    : Development/Tools
License  : GPL-2.0
Requires: libnetfilter_queue-lib
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(libnfnetlink)

%description
No detailed description available

%package dev
Summary: dev components for the libnetfilter_queue package.
Group: Development
Requires: libnetfilter_queue-lib
Provides: libnetfilter_queue-devel

%description dev
dev components for the libnetfilter_queue package.


%package lib
Summary: lib components for the libnetfilter_queue package.
Group: Libraries

%description lib
lib components for the libnetfilter_queue package.


%prep
%setup -q -n libnetfilter_queue-1.0.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1511114470
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1511114470
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/libnetfilter_queue/libnetfilter_queue.h
/usr/include/libnetfilter_queue/libnetfilter_queue_ipv4.h
/usr/include/libnetfilter_queue/libnetfilter_queue_ipv6.h
/usr/include/libnetfilter_queue/libnetfilter_queue_tcp.h
/usr/include/libnetfilter_queue/libnetfilter_queue_udp.h
/usr/include/libnetfilter_queue/linux_nfnetlink_queue.h
/usr/include/libnetfilter_queue/pktbuff.h
/usr/lib64/libnetfilter_queue.so
/usr/lib64/pkgconfig/libnetfilter_queue.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libnetfilter_queue.so.1
/usr/lib64/libnetfilter_queue.so.1.4.0
